env:
  TERM: xterm-256color
window:
  decorations: full
  title: "👨‍💻"
  dynamic_title: false
  padding:
    x: 6
    y: 6
  opacity: 1
scrolling:
  history: 100000
  multiplier: 3
font:
  normal:
    family: "BerkeleyMono Nerd Font"
    style: Regular
  italic:
    family: "BerkeleyMono Nerd Font"
    style: Italic
  bold:
    family: "BerkeleyMono Nerd Font"
    style: Bold
  size: 22.0

