[time]
disabled = false
format = "[$time]($style)"
time_format = '%H:%M'
style = "#bae6fd"

[custom.osstats]
command = "osstats terminal"
when = """ [[ "$PWD" == ~/github.com* ]] """
style = "#bae6fd"
format = "~ [$output]($style) "
